package dev.toma.vehiclemod.init;

import dev.toma.vehiclemod.VehicleMod;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

@GameRegistry.ObjectHolder(VehicleMod.MODID)
public class VMSounds {
    public static final SoundEvent BEAMER_ACC = null;
    public static final SoundEvent BEAMER_BRAKE = null;
    public static final SoundEvent BEAMER_GAS = null;
    public static final SoundEvent BEAMER_START = null;
    public static final SoundEvent TRACER_ACC = null;
    public static final SoundEvent TRACER_BRAKE = null;
    public static final SoundEvent TRACER_GAS = null;
    public static final SoundEvent TRACER_START = null;
    public static final SoundEvent FEDORATTI_ACC = null;
    public static final SoundEvent FEDORATTI_BRAKE = null;
    public static final SoundEvent FEDORATTI_GAS = null;
    public static final SoundEvent FEDORATTI_START = null;
    public static final SoundEvent SPUTNIK_ACC = null;
    public static final SoundEvent SPUTNIK_BRAKE = null;
    public static final SoundEvent SPUTNIK_GAS = null;
    public static final SoundEvent SPUTNIK_START = null;
    public static final SoundEvent BEAMERB1_ACC = null;
    public static final SoundEvent BEAMERB1_BRAKE = null;
    public static final SoundEvent BEAMERB1_GAS = null;
    public static final SoundEvent BEAMERB1_START = null;
    public static final SoundEvent MCGMV_ACC = null;
    public static final SoundEvent MCGMV_BRAKE = null;
    public static final SoundEvent MCGMV_GAS = null;
    public static final SoundEvent MCGMV_START = null;
    public static final SoundEvent BEAMERPICKUP_ACC = null;
    public static final SoundEvent BEAMERPICKUP_BRAKE = null;
    public static final SoundEvent BEAMERPICKUP_GAS = null;
    public static final SoundEvent BEAMERPICKUP_START = null;
    public static final SoundEvent SPUTNIK3_ACC = null;
    public static final SoundEvent SPUTNIK3_BRAKE = null;
    public static final SoundEvent SPUTNIK3_GAS = null;
    public static final SoundEvent SPUTNIK3_START = null;
    public static final SoundEvent SPUTNIK_DUSTER_ACC = null;
    public static final SoundEvent SPUTNIK_DUSTER_BRAKE = null;
    public static final SoundEvent SPUTNIK_DUSTER_GAS = null;
    public static final SoundEvent SPUTNIK_DUSTER_START = null;
    public static final SoundEvent FEDORATTI_NIGHTSTALKER_ACC = null;
    public static final SoundEvent FEDORATTI_NIGHTSTALKER_BRAKE = null;
    public static final SoundEvent FEDORATTI_NIGHTSTALKER_GAS = null;
    public static final SoundEvent FEDORATTI_NIGHTSTALKER_START = null;
    public static final SoundEvent PROTON_P1_ACC = null;
    public static final SoundEvent PROTON_P1_BRAKE = null;
    public static final SoundEvent PROTON_P1_GAS = null;
    public static final SoundEvent PROTON_P1_START = null;
    public static final SoundEvent PROTON_P1_TUNNED_ACC = null;
    public static final SoundEvent PROTON_P1_TUNNED_BRAKE = null;
    public static final SoundEvent PROTON_P1_TUNNED_GAS = null;
    public static final SoundEvent PROTON_P1_TUNNED_START = null;
    public static final SoundEvent SPUTNIK_AMBULANCE_ACC = null;
    public static final SoundEvent SPUTNIK_AMBULANCE_BRAKE = null;
    public static final SoundEvent SPUTNIK_AMBULANCE_GAS = null;
    public static final SoundEvent SPUTNIK_AMBULANCE_START = null;
    public static final SoundEvent SPUTNIK_FIRETRUCK_ACC = null;
    public static final SoundEvent SPUTNIK_FIRETRUCK_BRAKE = null;
    public static final SoundEvent SPUTNIK_FIRETRUCK_GAS = null;
    public static final SoundEvent SPUTNIK_FIRETRUCK_START = null;
    public static final SoundEvent SECRET = null;
    public static final SoundEvent LOCK_UNLOCKED = null;
    public static final SoundEvent LOCKPICK_SUCCESS = null;
    public static final SoundEvent LOCKPICK_FAILED = null;
    public static final SoundEvent LOCKPICK_FAILED_AF = null;
    public static final SoundEvent CAR_LOCKED = null;
    public static final SoundEvent CAR_UNLOCKED = null;
    public static final SoundEvent POLICE_SIREN = null;
    public static final SoundEvent AMBULANCE_SIREN = null;
    public static final SoundEvent FIRETRUCK_SIREN = null;
    public static final SoundEvent HORN_1 = null;
    public static final SoundEvent HORN_2 = null;
    public static final SoundEvent HORN_3 = null;
    public static final SoundEvent HORN_5 = null;
    public static final SoundEvent HORN_6 = null;
    public static final SoundEvent HORN_8 = null;
    public static final SoundEvent HORN_9 = null;
    public static final SoundEvent HORN_11 = null;
    public static final SoundEvent HORN_12 = null;
    public static final SoundEvent HORN_13 = null;
    public static final SoundEvent HORN_15 = null;
    public static final SoundEvent HORN_29S = null;
}
